services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: acme
    ports:
      - "5433:5432"
    volumes:
      - acme_data:/var/lib/postgresql/data

volumes:
  acme_data:
